spring:
  datasource:
    hikari:
      jdbc-url: "jdbc:mysql://localhost:3307/dddtutorial?characterEncoding=UTF-8&useTimezone=true&serverTimezone=Asia/Seoul"
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ddd
      password: ddd
      maximum-pool-size: 40
      minimum-idle: 40
      pool-name: hikari

log4jdbc:
  dump:
    sql:
      addsemicolon: true
      maxlinelength: 0
  trim.sql.extrablanklines: false

logging:
  level:
    com.bory.dddtutorial: DEBUG
    jdbc:
      resultsettable: info
      sqltiming: info
      sqlonly: fatal
      audit: fatal
      resultset: fatal
      connection: fatal
